name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups

      - name: Run ruff check
        run: uv run ruff check .

      - name: Run ruff format check
        run: uv run ruff format --check .

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-groups

      - name: Run pytest
        run: uv run pytest
