name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/gitwhodid
    steps:
      - uses: ./.github/actions/setup

      - name: Build wheel
        run: uv build

      - name: Publish package
        run: uv publish
